export const GET_ISSUES_DEBTS_REQUEST = 'debts/GET_ISSUES_DEBTS_REQUEST';
export const GET_ISSUES_DEBTS_SUCCESS = 'debts/GET_ISSUES_DEBTS_SUCCESS';
export const GET_OFFERS_DEBTS_REQUEST = 'debts/GET_OFFERS_DEBTS_REQUEST';
export const GET_OFFERS_DEBTS_SUCCESS = 'debts/GET_OFFERS_DEBTS_SUCCESS';
export const REPAY_DEBT_REQUEST = 'debts/REPAY_DEBT_REQUEST';
