export const CURRENT_USER_UPDATE_REQUEST = 'accout_edit/CURRENT_USER_UPDATE_REQUEST';
export const CURRENT_USER_UPDATE_SUCCESS = 'accout_edit/CURRENT_USER_UPDATE_SUCCESS';
export const CURRENT_USER_UPDATE_ERROR = 'accout_edit/CURRENT_USER_UPDATE_ERROR';
export const CURRENT_USER_UPDATE_PASSWORD_REQUEST = 'accout_edit/CURRENT_USER_UPDATE_PASSWORD_REQUEST';
