export const GET_SUITABLE_ISSUES_REQUEST = 'searchContainer/GET_SUITABLE_ISSUES_REQUEST';
export const GET_SUITABLE_OFFERS_REQUEST = 'searchContainer/GET_SUITABLE_OFFERS_REQUEST';
export const GET_SUITABLE_ISSUES_SUCCESS = 'searchContainer/GET_SUITABLE_ISSUES_SUCCESS';
export const GET_SUITABLE_OFFERS_SUCCESS = 'searchContainer/GET_SUITABLE_OFFERS_SUCCESS';
export const CREATE_MATCH_REQUEST = 'searchContainer/CREATE_MATCH_REQUEST';
