export const GET_ISSUES_REQUEST = 'myAnswers/GET_ISSUES_REQUEST';
export const GET_OFFERS_REQUEST = 'myAnswers/GET_OFFERS_REQUEST';
export const GET_ISSUES_SUCCESS = 'myAnswers/GET_ISSUES_SUCCESS';
export const GET_OFFERS_SUCCESS = 'myAnswers/GET_OFFERS_SUCCESS';
export const SUBMIT_NEW_ISSUE_REQUEST = 'myAnswers/SUBMIT_NEW_ISSUE_REQUEST';
export const SUBMIT_NEW_OFFER_REQUEST = 'myAnswers/SUBMIT_NEW_OFFER_REQUEST';
export const CLOSE_ISSUE_REQUEST = 'myAnswers/CLOSE_ISSUE_REQUEST';
export const CLOSE_OFFER_REQUEST = 'myAnswers/CLOSE_OFFER_REQUEST';
